import {Hono} from 'hono';
import {Database} from 'bun:sqlite';
import {serveStatic} from '@hono/node-server/serve-static';
import {error, scopes, type ProviderId, type Scope, type Session, type TranscriptEvent, signCursor, verifyCursor} from '@omonative/protocol';
import {registry, type LiveProvider, type ProviderCapability} from './providers';

type Options={secret:string;dbPath?:string;staticRoot?:string;fixtures?:boolean;providers?:Map<ProviderId,LiveProvider>;peerLoopback?:(request:Request)=>boolean}; type Cursor={provider:ProviderId;sessionId:string;generation:number;after:number};
const hash=(v:string)=>new Bun.CryptoHasher('sha256').update(v).digest('hex'), now=()=>new Date().toISOString(), id=(p:string)=>`${p}-${crypto.randomUUID()}`;
export function assertSafeBind(host:string){if(!['127.0.0.1','localhost','::1'].includes(host))throw new Error('Gateway may only bind loopback; use Tailscale Serve for remote access');}
export function issuePairingCode(dbPath:string){const db=new Database(dbPath);db.run('CREATE TABLE IF NOT EXISTS pairing_codes (hash TEXT PRIMARY KEY, expires INTEGER NOT NULL)');const code=crypto.randomUUID().slice(0,8);db.query('INSERT INTO pairing_codes(hash,expires) VALUES(?,?)').run(hash(code),Date.now()+300000);return code;}
const publicError=(code:string,status:number)=>error(code,code==='provider_unavailable'?'Provider unavailable':'Provider operation failed');
export function createGateway({secret,dbPath=':memory:',staticRoot,fixtures:fixtureOption,providers:injected,peerLoopback}:Options){
 const app=new Hono(),db=new Database(dbPath),providers=injected??registry(),fixtures=fixtureOption??process.env.OMONATIVE_FIXTURES==='1'; const isLoopback=peerLoopback??((fixtures||injected) ? ((request:Request)=>new URL(request.url).hostname==='localhost'||new URL(request.url).hostname==='127.0.0.1'||new URL(request.url).hostname==='::1') : (()=>false)); const events=new Map<string,TranscriptEvent[]>(), listeners=new Map<string,Set<(e:TranscriptEvent)=>void>>(), codes=new Map<string,{hash:string;expires:number}>(), capabilities=new Map<ProviderId,ProviderCapability>();
 db.run('CREATE TABLE IF NOT EXISTS control_tokens (id TEXT PRIMARY KEY, hash TEXT UNIQUE NOT NULL, scopes TEXT NOT NULL, revoked INTEGER NOT NULL DEFAULT 0, created_at TEXT NOT NULL, revoked_at TEXT)'); db.run('CREATE TABLE IF NOT EXISTS pairing_codes (hash TEXT PRIMARY KEY, expires INTEGER NOT NULL)'); db.run('CREATE TABLE IF NOT EXISTS sessions (id TEXT PRIMARY KEY, provider TEXT NOT NULL, project_id TEXT NOT NULL, title TEXT NOT NULL, generation INTEGER NOT NULL, updated_at TEXT NOT NULL, status TEXT NOT NULL)'); db.run('CREATE TABLE IF NOT EXISTS audit_metadata (id INTEGER PRIMARY KEY, action TEXT NOT NULL, token_id TEXT, at TEXT NOT NULL)');
 const audit=(action:string,token?:string)=>db.query('INSERT INTO audit_metadata(action,token_id,at) VALUES(?,?,?)').run(action,token??null,now());
 const rowSession=(r:any):Session=>({id:r.id,provider:r.provider,projectId:r.project_id,title:r.title,generation:r.generation,updatedAt:r.updated_at,status:r.status}); const session=(sid:string)=>{const r=db.query('SELECT * FROM sessions WHERE id=?').get(sid);return r?rowSession(r):undefined;}; const save=(s:Session)=>db.query('INSERT OR REPLACE INTO sessions(id,provider,project_id,title,generation,updated_at,status) VALUES(?,?,?,?,?,?,?)').run(s.id,s.provider,s.projectId,s.title,s.generation,s.updatedAt,s.status); if(fixtures) for(const provider of ['senpi','grok'] as ProviderId[]){const fixture={id:`${provider}-fixture`,provider,projectId:'fixture',title:`${provider} fixture`,generation:0,updatedAt:now(),status:'idle'} as Session;if(!session(fixture.id))save(fixture);events.set(fixture.id,[]);}
 const publish=(s:Session,event:Omit<TranscriptEvent,'id'|'generation'|'at'>):TranscriptEvent=>{const list=events.get(s.id)??[];events.set(s.id,list);const item={...event,id:list.length+1,generation:s.generation,at:now()} as TranscriptEvent;list.push(item);for(const fn of listeners.get(s.id)??[])fn(item);return item;};
 const tokenFor=(c:any,scope:Scope)=>{const raw=c.req.header('authorization')?.replace(/^Bearer /,'');if(!raw)return {kind:'missing'} as const;const r=db.query('SELECT id,scopes,revoked FROM control_tokens WHERE hash=?').get(hash(raw)) as any;if(!r||r.revoked)return {kind:'invalid'} as const;if(!(JSON.parse(r.scopes) as Scope[]).includes(scope))return {kind:'forbidden'} as const;return {kind:'valid',token:r} as const;}; const auth=(scope:Scope)=>(c:any,next:any)=>{const result=tokenFor(c,scope);if(result.kind!=='valid'){const unauthorized=result.kind!=='forbidden';return c.json(error(unauthorized?'unauthorized':'forbidden',unauthorized?'Bearer token required or revoked':'Required scope missing'),unauthorized?401:403);}c.set('token',result.token);return next();};
 const generation=(match:string|undefined)=>{if(!match)return undefined;const expected=Number(match.match(/^"generation-(\d+)"$/)?.[1]);return Number.isInteger(expected)?expected:null;}; const reserve=(sid:string,match:string|undefined,status:Session['status'])=>{const expected=generation(match);if(expected===undefined)return {code:428};if(expected===null)return {code:409};const changed=db.query('UPDATE sessions SET generation=generation+1,status=?,updated_at=? WHERE id=? AND generation=?').run(status,now(),sid,expected);if(changed.changes!==1)return{code:409};return{value:session(sid)!};}; const claimCancellation=(sid:string,match:string|undefined)=>{const expected=generation(match);if(expected===undefined)return {code:428};if(expected===null)return {code:409};const current=session(sid);if(!current||current.status!=='streaming'||(expected!==current.generation&&expected!==current.generation-1))return {code:409};const changed=db.query("UPDATE sessions SET status='cancelling',updated_at=? WHERE id=? AND generation=? AND status='streaming'").run(now(),sid,current.generation);if(changed.changes!==1)return {code:409};return {value:session(sid)!};}; const complete=(s:Session,status:Session['status'])=>{s.status=status;s.updatedAt=now();save(s);return s;}; const completeStreaming=(s:Session,status:Session['status'])=>{const changed=db.query('UPDATE sessions SET status=?,updated_at=? WHERE id=? AND generation=? AND status=?').run(status,now(),s.id,s.generation,'streaming');return changed.changes===1?session(s.id)!:session(s.id)!;};
 app.use('*',async(c,next)=>{c.header('X-Content-Type-Options','nosniff');c.header('Referrer-Policy','no-referrer');c.header('Content-Security-Policy',"default-src 'self'; connect-src 'self'; base-uri 'none'; frame-ancestors 'none'");if(c.req.path.startsWith('/api/'))c.header('Cache-Control','no-store');await next();});
 app.get('/api/v1/health',c=>c.json({ok:true,bind:'loopback'}));
 app.post('/api/v1/pairing/request',c=>{if(!isLoopback(c.req.raw))return c.json(error('loopback_required','Pairing bootstrap is available only through local CLI or trusted loopback integration'),403);const code=crypto.randomUUID().slice(0,8);codes.set(code,{hash:hash(code),expires:Date.now()+300000});audit('pairing.request');return c.json({code,expiresIn:300});});
 app.post('/api/v1/pairing/exchange',async c=>{const b=await c.req.json().catch(()=>({}));const stored=typeof b.code==='string'?codes.get(b.code):undefined;const durable=typeof b.code==='string'?db.query('SELECT expires FROM pairing_codes WHERE hash=?').get(hash(b.code)) as {expires:number}|null:null;if((!stored&&!durable)||((stored?.expires??durable!.expires)<Date.now())||(stored&&stored.hash!==hash(b.code)))return c.json(error('invalid_pairing','Code invalid, used, or expired'),400);codes.delete(b.code);if(durable)db.query('DELETE FROM pairing_codes WHERE hash=?').run(hash(b.code));const granted=(Array.isArray(b.scopes)?b.scopes:[]).filter((x:string)=>(scopes as string[]).includes(x)) as Scope[];const raw=`omo_${crypto.randomUUID()}`,tokenId=id('device');db.query('INSERT INTO control_tokens(id,hash,scopes,revoked,created_at) VALUES(?,?,?,0,?)').run(tokenId,hash(raw),JSON.stringify(granted),now());audit('pairing.exchange',tokenId);return c.json({token:raw,tokenId,scopes:granted});});
 app.get('/api/v1/providers',auth('metadata:read'),async c=>{for(const p of providers.values())capabilities.set(p.id,await p.capability());return c.json({providers:['senpi','grok'].map(x=>capabilities.get(x as ProviderId)??{id:x,available:false,capabilities:[],detail:'unavailable'})});});app.get('/api/v1/projects',auth('metadata:read'),c=>c.json({projects:[{id:'fixture',title:'Fixture project'}]}));
 app.get('/api/v1/sessions',auth('metadata:read'),async c=>{if(!fixtures){for(const p of providers.values()){try{for(const remote of await p.list()){const old=session(remote.id);save({...remote,generation:old?.generation??remote.generation,status:old?.status??remote.status});}}catch{}}}return c.json({sessions:(db.query('SELECT * FROM sessions ORDER BY updated_at DESC').all()as any[]).map(rowSession)});});
 app.get('/api/v1/sessions/:id',auth('metadata:read'),async c=>{const sid=c.req.param('id');let s=session(sid);if(!s){const failures:string[]=[];for(const p of providers.values())try{const loaded=await p.load(sid);s={...loaded,generation:1};save(s);break;}catch(e){failures.push(String(e));}if(!s&&failures.some(x=>!x.includes('not_found')))return c.json(publicError('provider_unavailable',502),502);}return s?c.json({session:s}):c.json(error('not_found','Session not found'),404);});
 app.post('/api/v1/sessions',auth('session:create'),async c=>{const b=await c.req.json().catch(()=>({}));if(!['senpi','grok'].includes(b.provider))return c.json(error('invalid_provider','Unknown provider'),400);const p=providers.get(b.provider);const cap=p&&await p.capability();if(!fixtures&&(!p||!cap?.available||!cap.capabilities.includes('create')))return c.json(publicError('provider_unavailable',501),501);const s:Session=fixtures?{id:id(b.provider),provider:b.provider,projectId:b.projectId??'fixture',title:b.title??'Untitled',generation:0,updatedAt:now(),status:'idle'}:await p!.create(b.projectId??process.cwd(),b.title);save(s);events.set(s.id,[]);audit('session.create',(c as any).get('token').id);return c.json({session:s},201);});
 app.get('/api/v1/sessions/:id/transcript',auth('transcript:read'),async c=>{const s=session(c.req.param('id'));if(!s)return c.json(error('not_found','Session not found'),404);if(fixtures)return c.json({events:events.get(s.id)??[]});const p=providers.get(s.provider);try{return c.json({events:await p!.transcript(s.id)});}catch{return c.json(publicError('provider_unavailable',502),502);}});
 app.get('/api/v1/sessions/:id/events',auth('transcript:read'),async c=>{const s=session(c.req.param('id'));if(!s)return c.json(error('not_found','Session not found'),404);let after=0;const raw=c.req.query('cursor');if(raw){const x=await verifyCursor(raw,secret)as Cursor|null;if(!x||x.sessionId!==s.id||x.provider!==s.provider)return c.json(error('invalid_cursor','Malformed cursor'),400);if(x.generation!==s.generation)return c.json(error('stale_generation','Replay cursor is from a stale generation'),409);after=x.after;}if(!fixtures)try{events.set(s.id,await providers.get(s.provider)!.transcript(s.id));}catch{return c.json(publicError('provider_unavailable',502),502);}const snapshot=(events.get(s.id)??[]).filter(e=>e.id>after);const stream=new ReadableStream({start:async controller=>{let sequence=after;const emit=async(e:TranscriptEvent)=>{sequence=e.id;controller.enqueue(`event: ${e.type}\ndata: ${JSON.stringify(e)}\n\n`);controller.enqueue(`event: cursor\ndata: ${JSON.stringify({cursor:await signCursor({provider:s.provider,sessionId:s.id,generation:e.generation,after:sequence},secret)})}\n\n`);};for(const e of snapshot)await emit(e);if(fixtures){controller.close();return;}const set=listeners.get(s.id)??new Set();listeners.set(s.id,set);const listener=(e:TranscriptEvent)=>void emit(e);set.add(listener);const beat=setInterval(()=>controller.enqueue(': heartbeat\n\n'),15000);c.req.raw.signal.addEventListener('abort',()=>{clearInterval(beat);set.delete(listener);try{controller.close();}catch{}},{once:true});}});return new Response(stream,{headers:{'content-type':'text/event-stream','cache-control':'no-store','connection':'keep-alive'}});});
 app.post('/api/v1/sessions/:id/messages',auth('session:send'),async c=>{const original=session(c.req.param('id'));if(!original)return c.json(error('not_found','Session not found'),404);const b=await c.req.json().catch(()=>({}));if(typeof b.text!=='string'||!b.text)return c.json(error('invalid_message','Text required'),400);const r=reserve(original.id,c.req.header('if-match'),'streaming');if(r.code)return c.json(error(r.code===428?'precondition_required':'stale_generation',r.code===428?'If-Match required':'Session changed'),r.code as any);const s=r.value!;try{if(fixtures){publish(s,{type:'message',role:'user',text:b.text});publish(s,{type:'message',role:'assistant',text:'REMOTE_OK'});publish(s,{type:'complete'});}else{const p=providers.get(s.provider);await p!.send(s.id,b.text);for(const e of await p!.transcript(s.id))publish(s,{type:e.type,role:e.role,text:e.text});}const completed=completeStreaming(s,'idle');audit('session.send',(c as any).get('token').id);return c.json({session:completed,events:events.get(s.id)??[]});}catch{completeStreaming(s,'idle');return c.json(publicError('provider_unavailable',502),502);}});
 app.post('/api/v1/sessions/:id/cancel',auth('session:cancel'),async c=>{const original=session(c.req.param('id'));if(!original)return c.json(error('not_found','Session not found'),404);const b=await c.req.json().catch(()=>({}));if(!b.confirm)return c.json(error('confirm_required','Explicit confirm required'),400);const expected=generation(c.req.header('if-match'));if(expected===undefined)return c.json(error('precondition_required','If-Match required'),428);if(expected===null)return c.json(error('stale_generation','Session changed'),409);const provider=fixtures?undefined:providers.get(original.provider);if(!fixtures){const cap=provider&&await provider.capability();if(!cap?.capabilities.includes('cancel'))return c.json(error('capability_not_supported','Provider cancel unsupported'),501);}const r=claimCancellation(original.id,c.req.header('if-match'));if(r.code)return c.json(error(r.code===428?'precondition_required':'stale_generation',r.code===428?'If-Match required':'Session changed'),r.code as any);const s=r.value!;try{if(provider)await provider.cancel(s.id);publish(s,{type:'cancelled'});complete(s,'cancelled');audit('session.cancel',(c as any).get('token').id);return c.json({session:s});}catch{db.query("UPDATE sessions SET status='streaming',updated_at=? WHERE id=? AND generation=? AND status='cancelling'").run(now(),s.id,s.generation);return c.json(publicError('provider_unavailable',502),502);}});
 app.post('/api/v1/tokens/revoke',auth('token:manage'),async c=>{const b=await c.req.json();db.query('UPDATE control_tokens SET revoked=1,revoked_at=? WHERE id=?').run(now(),b.tokenId);audit('token.revoke',(c as any).get('token').id);return c.json({revoked:true});});
 if(staticRoot){app.use('/*',async(c,next)=>{const path=c.req.path;if(path.startsWith('/assets/'))c.header('Cache-Control','public, max-age=31536000, immutable');else if(path==='/index.html'||path==='/manifest.webmanifest'||path==='/sw.js'||path==='/registerSW.js'||path.endsWith('/icon.png')||path==='/icon.png')c.header('Cache-Control','no-cache');else c.header('Cache-Control','no-cache');await next();},serveStatic({root:staticRoot}));app.get('*',serveStatic({path:`${staticRoot}/index.html`}));} return app;
}
