import {spawn} from 'bun';
import {readFile, realpath} from 'node:fs/promises';
import {relative, resolve} from 'node:path';
import {parseSessionEntries} from '@code-yeongyu/senpi-coding-agent/session-readonly';
import type {ProviderId, Session, TranscriptEvent} from '@omonative/protocol';

export type ProviderCapability = {id: ProviderId; available: boolean; transport: string; detail: string; capabilities: string[]};
export type LiveProvider = {id: ProviderId; capability(): Promise<ProviderCapability>; list(): Promise<Session[]>; create(cwd: string, title?: string): Promise<Session>; load(id: string): Promise<Session>; transcript(id: string): Promise<TranscriptEvent[]>; send(id: string, text: string): Promise<void>; cancel(id: string): Promise<void>};
export type RpcNotification = {method: string; params?: any};
export type RpcPeer = {request(method: string, params?: unknown): Promise<any>; waitForNotification(predicate: (message: RpcNotification) => boolean, timeout?: number): Promise<RpcNotification>; initialize(): Promise<void>; close(): void};
type RpcTransport = {stdin: {write(value: string): void}; stdout: ReadableStream<Uint8Array>; stderr?: ReadableStream<Uint8Array>; exited: Promise<number>; kill(): void};
const clock = () => new Date().toISOString();
const message = (value: unknown) => value instanceof Error ? value.message : String(value);
const safeDetail = (value: unknown) => message(value).replace(/(?:[A-Za-z]:)?[/~][^\s:]+/g, '[redacted]').replace(/(?:api[_-]?key|token|secret|password)=\S+/ig, '$1=[redacted]').slice(0, 240);
const timeout = <T>(promise: Promise<T>, ms: number, label: string) => new Promise<T>((resolve, reject) => { const timer = setTimeout(() => reject(new Error(`${label} timed out`)), ms); promise.then(value => { clearTimeout(timer); resolve(value); }, error => { clearTimeout(timer); reject(error); }); });

/** Bounded, supervised newline-delimited JSON-RPC transport. */
export class NdjsonRpc implements RpcPeer {
  private nextId = 1; private pending = new Map<number, {resolve:(v:any)=>void; reject:(e:Error)=>void}>();
  private notifications: RpcNotification[] = []; private waiters = new Set<{predicate:(m:RpcNotification)=>boolean; resolve:(m:RpcNotification)=>void; reject:(e:Error)=>void; timer?:ReturnType<typeof setTimeout>}>();
  private closed?: Error; private stderrRing: string[] = []; private readonly requestTimeout: number;
  constructor(private transportOrCommand: string[] | RpcTransport, env?: Record<string,string|undefined>, requestTimeout = 30_000) {
    this.requestTimeout = requestTimeout;
    const transport = Array.isArray(transportOrCommand) ? spawn({cmd: transportOrCommand, env, stdin:'pipe', stdout:'pipe', stderr:'pipe'}) as unknown as RpcTransport : transportOrCommand;
    this.transport = transport; void this.read(transport.stdout, false); if (transport.stderr) void this.read(transport.stderr, true);
    void transport.exited.then(code => this.fail(new Error(`Senpi app-server exited (${code})`)), e => this.fail(new Error(`Senpi app-server exited: ${safeDetail(e)}`)));
  }
  private transport: RpcTransport;
  private fail(reason: Error) { if (this.closed) return; this.closed = reason; for (const p of this.pending.values()) p.reject(reason); this.pending.clear(); for (const w of this.waiters) { if(w.timer) clearTimeout(w.timer); w.reject(reason); } this.waiters.clear(); }
  private deliver(note: RpcNotification) { for (const waiter of this.waiters) if (waiter.predicate(note)) { this.waiters.delete(waiter); if(waiter.timer)clearTimeout(waiter.timer); waiter.resolve(note); return; } if (this.notifications.length >= 256) this.notifications.shift(); this.notifications.push(note); }
  private async read(stream: ReadableStream<Uint8Array>, stderr: boolean) { try { const reader=stream.getReader(), decoder=new TextDecoder(); let buffer=''; for (;;) { const {done,value}=await reader.read(); if(done) { if(!stderr) this.fail(new Error('Senpi app-server closed stdout')); return; } buffer += decoder.decode(value,{stream:true}); const lines=buffer.split('\n'); buffer=lines.pop()??''; for(const line of lines) { if(stderr) { if(this.stderrRing.length>=128)this.stderrRing.shift(); this.stderrRing.push(safeDetail(line)); continue; } try { const parsed=JSON.parse(line); if(typeof parsed.id==='number' && this.pending.has(parsed.id)) { const p=this.pending.get(parsed.id)!; this.pending.delete(parsed.id); parsed.error?p.reject(new Error('Senpi RPC failed')):p.resolve(parsed.result); } else if(typeof parsed.method==='string'&&!Object.hasOwn(parsed,'id')) this.deliver(parsed); } catch {} } } } catch(e) { this.fail(new Error(`Senpi app-server read failed: ${safeDetail(e)}`)); } }
  request(method:string, params:unknown={}) { if(this.closed)return Promise.reject(this.closed); const id=this.nextId++; const operation=new Promise<any>((resolve,reject)=>{ this.pending.set(id,{resolve,reject}); try {this.transport.stdin.write(`${JSON.stringify({id,method,params})}\n`);}catch(e){this.pending.delete(id);reject(e instanceof Error?e:new Error(String(e)));} }); return timeout(operation,this.requestTimeout,`Senpi RPC ${method}`).catch(e=>{ this.pending.delete(id); this.close(); throw e; }); }
  waitForNotification(predicate:(m:RpcNotification)=>boolean, wait=180_000) { if(this.closed)return Promise.reject(this.closed); const found=this.notifications.findIndex(predicate); if(found>=0)return Promise.resolve(this.notifications.splice(found,1)[0]!); return new Promise<RpcNotification>((resolve,reject)=>{ const waiter={predicate,resolve,reject,timer:undefined as ReturnType<typeof setTimeout>|undefined}; waiter.timer=setTimeout(()=>{this.waiters.delete(waiter);reject(new Error('Senpi notification timed out'));},wait);this.waiters.add(waiter); }); }
  async initialize(){ await this.request('initialize',{clientInfo:{name:'omonative',version:'1.0.0'},capabilities:{experimentalApi:false}}); this.transport.stdin.write(`${JSON.stringify({method:'initialized',params:{}})}\n`); }
  close(){ try{this.transport.kill();}finally{this.fail(new Error('Senpi app-server closed'));} }
}

export class SenpiAdapter implements LiveProvider {
  id:ProviderId='senpi'; private connection?:Promise<RpcPeer>; private activeTurns=new Map<string,string>(); private sessionPaths=new Map<string,string>();
  constructor(private env:Record<string,string|undefined>=process.env, private connect:()=>Promise<RpcPeer>=async()=>{const rpc=new NdjsonRpc(['senpi','app-server','--listen','stdio://'],this.env);await rpc.initialize();return rpc;}){}
  private rpc(){ if(!this.connection) this.connection=this.connect().catch(e=>{this.connection=undefined;throw e;}); return this.connection; }
  async close(){try{(await this.connection)?.close();}finally{this.connection=undefined;}}
  private session(thread:any):Session{return{id:thread.id,provider:'senpi',projectId:thread.cwd??'default',title:thread.name??thread.preview??thread.id,generation:0,updatedAt:new Date((thread.updatedAt??Date.now()/1000)*1000).toISOString(),status:thread.status?.type==='idle'?'idle':'streaming'};}
  private async cacheSessionPath(thread:any){if(typeof thread?.id!=='string'||typeof thread?.path!=='string')return;const root=this.env.SENPI_CODING_AGENT_SESSION_DIR;if(!root)throw new Error('Provider unavailable/read failed');try{const [sessionRoot,sessionPath]=await Promise.all([realpath(resolve(root)),realpath(resolve(thread.path))]);const rel=relative(sessionRoot,sessionPath);if(rel===''||rel.startsWith('..')||resolve(sessionRoot,rel)!==sessionPath)throw new Error('outside session root');this.sessionPaths.set(thread.id,sessionPath);}catch{throw new Error('Provider unavailable/read failed');}}
  private async cacheThreads(threads:any[]){await Promise.all(threads.map(thread=>this.cacheSessionPath(thread)));}
  private liveTranscript(response:any){const out:TranscriptEvent[]=[];const turns=Array.isArray(response.thread?.turns)&&response.thread.turns.length?response.thread.turns:Array.isArray(response.turns)?response.turns:[];for(const turn of turns)for(const item of turn?.items??[]){const role=item.type==='userMessage'?'user':item.type==='agentMessage'||item.type==='assistantMessage'?'assistant':undefined;const text=typeof item.text==='string'?item.text:Array.isArray(item.content)?item.content.filter((part:any)=>part?.type==='text'&&typeof part.text==='string').map((part:any)=>part.text).join(''):'';if(role&&text)out.push({id:out.length+1,type:'message',role,text,generation:0,at:clock()});}return out;}
  private async archivedTranscript(id:string){const path=this.sessionPaths.get(id);if(!path)throw new Error('Provider unavailable/read failed');try{const entries=parseSessionEntries(await readFile(path,'utf8')) as Array<any>;const out:TranscriptEvent[]=[];for(const entry of entries){const role=entry?.type==='message'&&['user','assistant'].includes(entry.message?.role)?entry.message.role:undefined;const text=role&&Array.isArray(entry.message.content)?entry.message.content.filter((part:any)=>part?.type==='text'&&typeof part.text==='string').map((part:any)=>part.text).join(''):'';if(role&&text)out.push({id:out.length+1,type:'message',role,text,generation:0,at:typeof entry.timestamp==='string'?entry.timestamp:clock()});}return out;}catch{throw new Error('Provider unavailable/read failed');}}
  async capability():Promise<ProviderCapability>{try{const rpc=await this.rpc();await rpc.request('thread/list',{limit:1});return{id:'senpi',available:true,transport:'senpi app-server stdio JSON-RPC',detail:'live app-server',capabilities:['list','create','load','send','cancel','transcript']};}catch{return{id:'senpi',available:false,transport:'senpi app-server stdio JSON-RPC',detail:'Provider unavailable',capabilities:[]};}}
  async list():Promise<Session[]>{try{const r=await this.rpc();const x=await r.request('thread/list',{limit:100});const threads=Array.isArray(x.data)?x.data:[];await this.cacheThreads(threads);return threads.map((t:any)=>this.session(t));}catch{throw new Error('Provider unavailable/read failed');}}
  async create(cwd:string,title?:string){const r=await this.rpc();const x=await r.request('thread/start',{cwd});if(title)await r.request('thread/name/set',{threadId:x.thread.id,name:title});return this.session({...x.thread,name:title??x.thread.name});}
  async load(id:string){const x=await (await this.rpc()).request('thread/read',{threadId:id,includeTurns:false});return this.session(x.thread);}
  async transcript(id:string){try{const x=await (await this.rpc()).request('thread/read',{threadId:id,includeTurns:true});const live=this.liveTranscript(x);if(live.some(event=>event.role==='assistant')||!this.env.SENPI_CODING_AGENT_SESSION_DIR)return live;await this.list();return this.archivedTranscript(id);}catch{throw new Error('Provider unavailable/read failed');}}
  async send(id:string,text:string){if(this.activeTurns.has(id))throw new Error('session_busy'); const rpc=await this.rpc(); let turnId:string|undefined; try{await rpc.request('thread/resume',{threadId:id});const started=await rpc.request('turn/start',{threadId:id,input:[{type:'text',text}]});turnId=started?.turn?.id;if(typeof turnId!=='string')throw new Error('Senpi turn start failed');this.activeTurns.set(id,turnId);const completed=await rpc.waitForNotification(m=>m.method==='turn/completed'&&m.params?.threadId===id&&m.params?.turn?.id===turnId);if(completed.params?.turn?.status!=='completed')throw new Error(`Senpi turn ${completed.params?.turn?.status ?? 'failed'}`);}finally{if(turnId&&this.activeTurns.get(id)===turnId)this.activeTurns.delete(id);}}
  async cancel(id:string){const turnId=this.activeTurns.get(id);if(!turnId)throw new Error('capability_not_supported: no active Senpi turn is tracked for cancellation');await (await this.rpc()).request('turn/interrupt',{threadId:id,turnId});}
}

export class GrokAdapter implements LiveProvider { id:ProviderId='grok'; private roots=new Map<string,string>(); constructor(private env:Record<string,string|undefined>=process.env, private cwd=process.cwd()){} private environment(){const out:Record<string,string|undefined>={};for(const key of ['PATH','HOME','GROK_HOME','XAI_API_KEY','HTTPS_PROXY','HTTP_PROXY','NO_PROXY','GROK_MODEL'])if(this.env[key])out[key]=this.env[key];return out;} private async run(args:string[],cwd=this.cwd){const p=spawn({cmd:['grok',...args],env:this.environment(),cwd,stdout:'pipe',stderr:'pipe'});const[out,err,code]=await Promise.all([new Response(p.stdout).text(),new Response(p.stderr).text(),p.exited]);if(code!==0)throw new Error('Grok command failed');return out;} async capability():Promise<ProviderCapability>{try{await this.run(['sessions','list','--limit','1']);return{id:'grok',available:true,transport:'grok CLI',detail:'live CLI',capabilities:['list','create','load','send','transcript']};}catch{return{id:'grok',available:false,transport:'grok CLI',detail:'Provider unavailable',capabilities:[]};}} async list(){const o=await this.run(['sessions','list','--limit','100']);return o.split('\n').filter(x=>/^[0-9a-f]{8}-/i.test(x.trim())).map(x=>{const id=x.trim().split(/\s+/)[0];return{id,provider:'grok',projectId:this.roots.get(id)??this.cwd,title:x.trim().slice(id.length).trim()||id,generation:0,updatedAt:clock(),status:'idle'} as Session;});} async create(cwd:string,title?:string):Promise<Session>{const id=crypto.randomUUID();await this.run(['--cwd',cwd,'--session-id',id,'--single',title??'Omonative session bootstrap','--output-format','json','--max-turns','1'],cwd);this.roots.set(id,cwd);return{id,provider:'grok',projectId:cwd,title:title??id,generation:0,updatedAt:clock(),status:'idle'} as Session;} async load(id:string){const x=(await this.list()).find(s=>s.id===id);if(!x)throw new Error('not_found');return x;} async transcript(id:string):Promise<TranscriptEvent[]>{return[{id:1,type:'message',role:'assistant',text:await this.run(['export',id],this.roots.get(id)??this.cwd),generation:0,at:clock()}];} async send(id:string,text:string){const cwd=this.roots.get(id)??this.cwd;await this.run(['--cwd',cwd,'--resume',id,'--single',text,'--output-format','json','--max-turns','1'],cwd);}async cancel(){throw new Error('capability_not_supported: cancellation unavailable');}}
export function registry(env:Record<string,string|undefined>=process.env){return new Map<ProviderId,LiveProvider>([['senpi',new SenpiAdapter(env)],['grok',new GrokAdapter(env)]]);}
