import {beforeEach,expect,test} from 'bun:test'; import {mkdirSync,rmSync,writeFileSync} from 'node:fs'; import {join} from 'node:path'; import {tmpdir} from 'node:os'; import {createGateway} from '../apps/gateway/src/app';
let app: ReturnType<typeof createGateway>; let token:string;
beforeEach(async()=>{ app=createGateway({secret:'test',fixtures:true}); const r=await app.fetch(new Request('http://localhost/api/v1/pairing/request',{method:'POST'})); const {code}=await r.json() as any; const x=await app.fetch(new Request('http://localhost/api/v1/pairing/exchange',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({code,scopes:['metadata:read','transcript:read','session:create','session:send','session:cancel']})})); token=(await x.json() as any).token; });
const call=(path:string, init:RequestInit={})=>app.fetch(new Request('http://localhost'+path,{...init,headers:{authorization:`Bearer ${token}`,...init.headers}}));
test('lists metadata without transcript body and token revocation denies access',async()=>{const r=await call('/api/v1/sessions'); expect(r.status).toBe(200); const body=await r.json() as any; expect(body.sessions[0].text).toBeUndefined();});
test('requires generation, streams REMOTE_OK and rejects stale control',async()=>{let r=await call('/api/v1/sessions',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({provider:'senpi',projectId:'fixture',title:'x'})}); const s=(await r.json()as any).session; r=await call(`/api/v1/sessions/${s.id}/messages`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({text:'ping'})}); expect(r.status).toBe(428); r=await call(`/api/v1/sessions/${s.id}/messages`,{method:'POST',headers:{'content-type':'application/json','if-match':'"generation-0"'},body:JSON.stringify({text:'ping'})}); expect(r.status).toBe(200); expect(await r.text()).toContain('REMOTE_OK'); r=await call(`/api/v1/sessions/${s.id}/cancel`,{method:'POST',headers:{'content-type':'application/json','if-match':'"generation-0"'},body:JSON.stringify({confirm:true})});expect(r.status).toBe(409);});
test('rejects bad auth and malformed replay cursor',async()=>{expect((await app.fetch(new Request('http://localhost/api/v1/providers'))).status).toBe(401); expect((await call('/api/v1/sessions/senpi-fixture/events?cursor=broken')).status).toBe(400);});
test('revoked bearer token is unauthorized rather than scope-forbidden',async()=>{const revoke=await call('/api/v1/tokens/revoke',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({tokenId:'unknown'})}); expect(revoke.status).toBe(403); const privileged=await app.fetch(new Request('http://localhost/api/v1/pairing/request',{method:'POST'})); const {code}=await privileged.json() as any; const paired=await app.fetch(new Request('http://localhost/api/v1/pairing/exchange',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({code,scopes:['metadata:read','token:manage']})})); const device=await paired.json() as any; const revoked=await app.fetch(new Request('http://localhost/api/v1/tokens/revoke',{method:'POST',headers:{authorization:`Bearer ${device.token}`,'content-type':'application/json'},body:JSON.stringify({tokenId:device.tokenId})})); expect(revoked.status).toBe(200); expect((await app.fetch(new Request('http://localhost/api/v1/sessions',{headers:{authorization:`Bearer ${device.token}`}}))).status).toBe(401);});

test('serves pwa assets with correct cache-control',async()=>{const staticRoot=join(tmpdir(),`omonative-static-${crypto.randomUUID()}`); mkdirSync(join(staticRoot,'assets'),{recursive:true}); writeFileSync(join(staticRoot,'index.html'),'<!doctype html><html></html>'); writeFileSync(join(staticRoot,'manifest.webmanifest'),'{}'); writeFileSync(join(staticRoot,'sw.js'),'self.addEventListener("install",()=>{});'); writeFileSync(join(staticRoot,'registerSW.js'),'export{}'); writeFileSync(join(staticRoot,'icon.png'),'x'); writeFileSync(join(staticRoot,'assets/index-abc.js'),'console.log(1);'); const pwa=createGateway({secret:'test',staticRoot,fixtures:true}); const check=async(path:string)=>{const r=await pwa.fetch(new Request(`http://localhost${path}`)); return r.headers.get('cache-control');}; expect(await check('/sw.js')).toBe('no-cache'); expect(await check('/registerSW.js')).toBe('no-cache'); expect(await check('/index.html')).toBe('no-cache'); expect(await check('/manifest.webmanifest')).toBe('no-cache'); expect(await check('/icon.png')).toBe('no-cache'); expect(await check('/assets/index-abc.js')).toBe('public, max-age=31536000, immutable'); rmSync(staticRoot,{recursive:true,force:true});});
